# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip', models.CharField(blank=True, max_length=20, null=True)),
                ('draft', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('photos', models.ManyToManyField(blank=True, to='interior_app.Photo')),
            ],
        ),
    ]
