# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photos',
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interior_app.Photo'),
        ),
    ]
