# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0003_auto_20151229_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='portfolioobject',
            name='draft',
            field=models.ImageField(blank=True, null=True, upload_to='drafts'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
