# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0004_auto_20151229_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='photo6',
        ),
        migrations.AddField(
            model_name='photo',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interior_app.PortfolioObject'),
        ),
    ]
