# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0005_auto_20151229_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_photo', models.ImageField(blank=True, null=True, upload_to='article_photo')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interior_app.Article')),
            ],
        ),
    ]
