# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0006_article_articlephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'), ('\u041c\u043e\u0434\u0435\u0440\u043d', '\u041c\u043e\u0434\u0435\u0440\u043d'), ('\u041f\u043e\u0441\u0442-\u043c\u043e\u0434\u0435\u0440\u043d', '\u041f\u043e\u0441\u0442-\u043c\u043e\u0434\u0435\u0440\u043d'), ('\u0411\u0430\u0440\u043e\u043a\u043a\u043e', '\u0411\u0430\u0440\u043e\u043a\u043a\u043e'), ('\u0420\u043e\u043a\u043e\u043a\u043e', '\u0420\u043e\u043a\u043e\u043a\u043e'), ('\u0421\u043e\u0432\u0435\u0442\u044b', '\u0421\u043e\u0432\u0435\u0442\u044b')], default='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', max_length=1000),
            preserve_default=False,
        ),
    ]
