# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0007_auto_20160104_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
    ]
