# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0011_auto_20160112_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='name',
            field=models.CharField(choices=[('\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430', '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), ('\u0414\u043e\u043c', '\u0414\u043e\u043c'), ('\u041e\u0444\u0438\u0441', '\u041e\u0444\u0438\u0441'), ('\u0420\u0435\u0441\u0442\u043e\u0440\u0430\u043d', '\u0420\u0435\u0441\u0442\u043e\u0440\u0430\u043d')], max_length=50, verbose_name='\u0412\u044b\u0431\u043e\u0440 \u043f\u043e \u0442\u0438\u043f\u0443 \u043e\u0431\u044a\u0435\u043a\u0442\u0430:'),
        ),
    ]
