# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0013_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
