# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0014_auto_20160113_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interior_app.Subscriber')),
            ],
        ),
    ]
