# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0015_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
