# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0016_auto_20160116_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='active',
        ),
    ]
