# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0018_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioobject',
            name='sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interior_app.Sort'),
        ),
    ]
