# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior_app', '0019_auto_20160118_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0422\u0438\u043f \u043e\u0431\u044a\u0435\u043a\u0442\u0430:'),
        ),
    ]
